// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TournamentPlatformSystemWebApi.Infrastructure.Context;

#nullable disable

namespace TournamentPlatformSystemWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(TournamentdbContext))]
    [Migration("20260429080918_AddRefreshToken")]
    partial class AddRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tournament_status", "tournament_status_type", new[] { "registration_open", "registration_closed", "in_progress", "completed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.AccountStateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("account_state_pkey");

                    b.HasIndex(new[] { "Name" }, "account_state_name_key")
                        .IsUnique();

                    b.ToTable("account_state", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.MatchModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_valid");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_a_id");

                    b.Property<int?>("TeamAScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("team_a_score");

                    b.Property<Guid?>("TeamBId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_b_id");

                    b.Property<int?>("TeamBScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("team_b_score");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("match_pkey");

                    b.HasIndex(new[] { "IsValid" }, "idx_match_is_valid");

                    b.HasIndex(new[] { "Level" }, "idx_match_level");

                    b.HasIndex(new[] { "TeamAId" }, "idx_match_team_a_id");

                    b.HasIndex(new[] { "TeamBId" }, "idx_match_team_b_id");

                    b.HasIndex(new[] { "TournamentId" }, "idx_match_tournament_id");

                    b.HasIndex(new[] { "WinnerId" }, "idx_match_winner_id");

                    b.HasIndex(new[] { "TournamentId", "Level", "OrderNumber" }, "unique_match_position")
                        .IsUnique();

                    b.ToTable("match", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.RefreshTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_token_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsDisqualified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disqualified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("team_pkey");

                    b.HasIndex(new[] { "IsDisqualified" }, "idx_team_is_disqualified");

                    b.HasIndex(new[] { "TournamentId" }, "idx_team_tournament_id");

                    b.HasIndex(new[] { "Name", "TournamentId" }, "unique_team_name_per_tournament")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackgroundImg")
                        .HasColumnType("text")
                        .HasColumnName("background_img");

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer")
                        .HasColumnName("max_teams");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registration_deadline");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("tournament_status")
                        .HasColumnName("status");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("tournament_pkey");

                    b.HasIndex(new[] { "OrganizerId" }, "idx_tournament_organizer_id");

                    b.HasIndex(new[] { "RegistrationDeadline" }, "idx_tournament_registration_deadline");

                    b.HasIndex(new[] { "StartDate" }, "idx_tournament_start_date");

                    b.HasIndex(new[] { "ThemeId" }, "idx_tournament_theme_id");

                    b.ToTable("tournament", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentThemeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tournament_theme_pkey");

                    b.HasIndex(new[] { "Name" }, "tournament_theme_name_key")
                        .IsUnique();

                    b.ToTable("tournament_theme", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserDetailModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_details_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_user_details_email");

                    b.HasIndex(new[] { "UserId" }, "idx_user_details_user_id");

                    b.HasIndex(new[] { "Email" }, "user_details_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "user_details_user_id_key")
                        .IsUnique();

                    b.ToTable("user_details", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_state_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsOrganizer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_organizer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex(new[] { "AccountStateId" }, "idx_user_account_state_id");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_user_deleted_at");

                    b.HasIndex(new[] { "IsOrganizer" }, "idx_user_is_organizer");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserPhoneModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_phone_pkey");

                    b.HasIndex(new[] { "PhoneNumber" }, "idx_user_phone_phone_number");

                    b.HasIndex(new[] { "UserId" }, "idx_user_phone_user_id");

                    b.ToTable("user_phone", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserTeamModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_team_pkey");

                    b.HasIndex(new[] { "TeamId" }, "idx_user_team_team_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_team_user_id");

                    b.HasIndex(new[] { "UserId", "TeamId" }, "unique_user_team")
                        .IsUnique();

                    b.ToTable("user_team", (string)null);
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.MatchModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", "TeamA")
                        .WithMany("MatchTeamAs")
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("match_team_a_id_fkey");

                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", "TeamB")
                        .WithMany("MatchTeamBs")
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("match_team_b_id_fkey");

                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentModel", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("match_tournament_id_fkey");

                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", "Winner")
                        .WithMany("MatchWinners")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("match_winner_id_fkey");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.RefreshTokenModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_token_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentModel", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("team_tournament_id_fkey");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", "Organizer")
                        .WithMany("Tournaments")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tournament_organizer_id_fkey");

                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentThemeModel", "Theme")
                        .WithMany("Tournaments")
                        .HasForeignKey("ThemeId")
                        .IsRequired()
                        .HasConstraintName("tournament_theme_id_fkey");

                    b.Navigation("Organizer");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserDetailModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserDetailModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_details_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.AccountStateModel", "AccountState")
                        .WithMany("Users")
                        .HasForeignKey("AccountStateId")
                        .IsRequired()
                        .HasConstraintName("user_account_state_id_fkey");

                    b.Navigation("AccountState");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserPhoneModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", "User")
                        .WithMany("UserPhones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_phone_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserTeamModel", b =>
                {
                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_team_team_id_fkey");

                    b.HasOne("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_team_user_id_fkey");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.AccountStateModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TeamModel", b =>
                {
                    b.Navigation("MatchTeamAs");

                    b.Navigation("MatchTeamBs");

                    b.Navigation("MatchWinners");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentModel", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.TournamentThemeModel", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TournamentPlatformSystemWebApi.Infrastructure.Entities.UserModel", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Tournaments");

                    b.Navigation("UserDetail");

                    b.Navigation("UserPhones");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
